### PR TITLE
Make UseDNS configurable

### LINKED ISSUE #79: UseDNS no
Hey!

I'm suffering from very slow SSH logins (15-20 seconds), caused by `UseDNS yes`. I wondered what the security implications would be if I sent a PR enabling the cookbook user to define `yes` or `no` themselves. I couldn't quite find detailed information about the `UseDNS` option besides [this StackExchange post](http://unix.stackexchange.com/a/56947).

In the meantime, I'll prep a PR and await your answer.

### PR DESCRIPTION
**Pull request by aried3r**
Fixes #79.

### CODE REVIEW

**Comment by arlimus** [comment]
@aried3r Awesome, thank you for adding this
!
I'll merge it, though the default value will probably change. OpenSSH changed the UseDNS defaults on release 6.8. We will have another look at the security implications as well.

**Comment by arlimus** [comment]
For reference: http://www.openssh.com/txt/release-6.8

**Comment by aried3r** [comment]
I guess I could do the same as `AllowUsers` does, either setting whatever the user supplied, or adding the commented out directive (`#UseDNS yes`). [See here](https://github.com/hardening-io/chef-ssh-hardening/blob/master/templates/default/opensshd.conf.erb#L122-L125), that way if the user does not override this setting, the default OpenSSH behaviour will be used (afaik).

Also, I only added local rspec tests, they did not seem to be run when using `kitchen test default-ubuntu-1204, should I add them to the shared spec repo or how exactly do you guys maintain these?

**Comment by arlimus** [comment]
For tests: We run rspec/chefspec tests via `rake spec`. That always runs without kitchen.
For kitchen we add everything to the respective tests-repo, so https://github.com/hardening-io/tests-ssh-hardening in this case. If we find that AllowUsers has security implications, then the expectation will be added there.

Let's see if the defaults for UseDNS have security implications. If not, I'd prefer the solution of only setting it, if the user assigns a value. With the cookbook supporting more options, I think it's best to use this style of configuration.

**Comment by chris-rock** [comment]
If you use `bundle exec thor kitchen:fetch-remote-tests` you will fetch the tests into the tests folder. More information is available here: https://github.com/hardening-io/chef-ssh-hardening#local-testing. 

`kitchen test` only runs the integration tests (triggered by our jenkins environment)
`rake spec` will run the chef-spec (and called for each travis trigger)

**Comment by aried3r** [comment]
> rake spec will run the chef-spec (and called for each travis trigger)

On that note, I did not see a test run for my PR, are they not triggered by default?

**Comment by chris-rock** [comment]
Yes, we recently moved to a new github organization (last week). Something was broken with the Travis access rights. Right after your PR, I already fixed the travis connection. It should work with the next PR. I keep an eye on it.

**Comment by chris-rock** [comment]
@aried3r please add `AllowUsers`. We could extend it to support three states e.g.
```
default['ssh']['use_dns'] = nil -> commented out '#UseDNS yes'
default['ssh']['use_dns'] = 'yes' -> 'UseDNS yes'
default['ssh']['use_dns'] = 'no' -> 'UseDNS no'
```

**Pull request merged**
