### PR TITLE
Modern alogs for Jessie

### LINKED ISSUE #77: Debian 8.0 (Jessie) ships with OpenSSH 6.7p1, enable modern algos
as done with hardening-io/puppet-ssh-hardening/pull/44 we should enable the better ciphers for debian 8

### PR DESCRIPTION
**Pull request by Rockstar04**
Should be the exact equivalent changes made to the puppet repo. closes #77 

Also should we look into chefspec tests for those helpers, or just let serverspec cover it?

### CODE REVIEW

**Comment by chris-rock** [comment]
great work @Rockstar04 we need to get #84 through first

**Comment by Rockstar04** [comment]
I'm not sure what the proper Ruby way would be to restructure the "Assignment Branch Condition size for xxxx is too high." warnings that are stopping Travis.

**Comment by chris-rock** [comment]
this is a robocop error message. See https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/metrics/abc_size.rb

this is configured in: https://github.com/hardening-io/chef-ssh-hardening/blob/master/.rubocop.yml#L28

You can test this locally by using `rake lint`

**Comment by Rockstar04** [comment]
Sorry, I understood what the rubocop error was telling me, I am just unsure what the proper way to go about refactoring into something better

**Comment by arlimus** [comment]
@Rockstar04 thank you for adding Debian 8! :)

Regarding Rubocop: That ABC-linter points to some restructuring in the function. Mid-term we may as well increase this value, as in this case the coding-style that contributes to the error (those many assignments) is a matter of style and not complexity.

I re-ran all specs and lints; specs are clean, lint only shows Abc-error. Let's fix it in an upcoming commit.

**Pull request merged**
